### ISSUE TITLE
这是darknet里面yolov7-tiny吗如果是怎么转换onnx哦

### ISSUE THREAD

**Issue by futureflsl** [ivilson/Yolov7net#1]
我看默认是yolov7-tiny.onnx yolov7-pytorch版本并没有yolov7-tiny版本，darknet确有一个，只不过现在找不到将weights转换onnx代码

**Comment by iwaitu** [comment]
you can train your yolov7-tiny.pt with coco dataset by use params --cfg cfg/training/yolov7-tiny.yaml and export the e2e onnx model.
