### ISSUE TITLE
Yolov8 by any chanse?

### ISSUE THREAD

**Issue by subsneer** [ivilson/Yolov7net#10]
Hello, 
YoloV8 by any chance?

**Comment by iwaitu** [comment]
will coming soon

**Comment by subsneer** [comment]
Found one here https://github.com/sstainba/Yolov8.Net but would be nice to see your solution as well

**Comment by iwaitu** [comment]
Thank you for the information provided. I would like to test the performance comparison between this attempt using numsharp and another project you provided.
