### ISSUE TITLE
Predict “One or more errors occurred,(Index was outside the bounds of  the array)”

### ISSUE THREAD

**Issue by javaCR7** [ivilson/Yolov7net#25]
![image](https://github.com/ivilson/Yolov7net/assets/38103065/81c545a3-6c37-4eca-825b-a759716e79a0)

**Comment by javaCR7** [comment]
![image](https://github.com/ivilson/Yolov7net/assets/38103065/cb9a30dd-3edb-4171-805f-5a8a00067393)

**Comment by iwaitu** [comment]
If the onnx file is you custom train weight file ,you should setup the labels before your prediction. like this :

```
yolo.SetupLabels(string[] labels)；
```
