### ISSUE TITLE
识别结果Y坐标返回负值

### ISSUE THREAD

**Issue by MooWeii** [ivilson/Yolov7net#26]
作者可以给个邮箱或者其他联系方式吗, 我这里有张图片通过添加这个库引用识别出来的Y坐标为负值, 给您源码看下

**Comment by MooWeii** [comment]
![snipaste20240112_102349](https://github.com/ivilson/Yolov7net/assets/63271242/cb5a1799-418f-47db-a349-be41b39e316a)

如图

**Comment by iwaitu** [comment]
给个图片链接我试试？
