### ISSUE TITLE
cuda faild

### ISSUE THREAD

**Issue by dotecxy** [ivilson/Yolov7net#27]
![微信截图_20240114143659](https://github.com/ivilson/Yolov7net/assets/22089873/ea209d69-d0c1-4299-81fc-cf28dfea2d9a)
![Uploading 微信截图_20240114143659.png…]()

**Comment by iwaitu** [comment]
使用cuda 的话，你需要引用 Microsoft.ML.OnnxRuntime.Gpu 这个包
