### ISSUE TITLE
Yolov9

### ISSUE THREAD

**Issue by theo2f** [ivilson/Yolov7net#29]
Hi! Can I expect any news regarding Yolov9 soon?

**Comment by iwaitu** [comment]
Hi! I just noticed that YOLOv9 has already been released. I will catch up with it as soon as possible.

**Comment by iwaitu** [comment]
I have already conducted tests on the net8.0 branch, and found that yolov9 and yolov8 are compatible, so we can continue using the original code.

**Comment by theo2f** [comment]
Great!
