### ISSUE TITLE
调用异常

### ISSUE THREAD

**Issue by virgilKing** [ivilson/Yolov7net#3]
使用自己的模型报错信息：  lable与训练的lable是一致的   yolov5 类文件 

System.IndexOutOfRangeException
  HResult=0x80131508
  Message=Index was outside the bounds of the array.
  Source=System.Private.CoreLib
  StackTrace:
   在 System.ThrowHelper.ThrowIndexOutOfRangeException()
   在 System.Span`1.get_Item(Int32 index)
   在 Microsoft.ML.OnnxRuntime.Tensors.DenseTensor`1.GetValue(Int32 index)
   在 Microsoft.ML.OnnxRuntime.Tensors.Tensor`1.get_Item(ReadOnlySpan`1 indices)
   在 Microsoft.ML.OnnxRuntime.Tensors.Tensor`1.get_Item(Int32[] indices)
   在 Yolov7net.Yolov5.<>c__DisplayClass9_0.<ParseDetect>b__0(Int32 i) 
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)

使用自己的模型报错信息：  lable与训练的lable是一致的   yolov7 类文件 
System.IndexOutOfRangeException
  HResult=0x80131508
  Message=Index was outside the bounds of the array.
  Source=System.Private.CoreLib
  StackTrace:
   在 System.ThrowHelper.ThrowIndexOutOfRangeException()
   在 System.Span`1.get_Item(Int32 index)
   在 Microsoft.ML.OnnxRuntime.Tensors.DenseTensor`1.GetValue(Int32 index)
   在 Microsoft.ML.OnnxRuntime.Tensors.Tensor`1.get_Item(ReadOnlySpan`1 indices)
   在 Microsoft.ML.OnnxRuntime.Tensors.Tensor`1.get_Item(Int32[] indices)
   在 Yolov7net.Yolov7.<>c__DisplayClass6_0.<ParseDetect>b__0(Int32 i)
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)

**Comment by iwaitu** [comment]
You should clone this repository and rename your weights file xxx.onnx to yolov7-tiny.onnx if your onnx file is yolov7 with nms result format or yolov7-tiny_640x640.onnx if your onnx file is yolov5 format , then copy it to 
···
[respository path]\test\Yolov7net.test\Assets
···
and run or debug the yolov7net.test project.

**Comment by virgilKing** [comment]
Yeah, that's what I did, but I made a mistake

**Comment by iwaitu** [comment]
parse your code here and i can find out what happend

**Comment by lostmsu** [comment]
Can you link to a suitable .onnx? I tried a few from https://github.com/WongKinYiu/yolov7/releases and get the same error with any one of them no matter how I rename the file.
