### ISSUE TITLE
System.Drawing.Common is only usable on Windows

### ISSUE THREAD

**Issue by sharpwood** [ivilson/Yolov7net#30]
System.Drawing.Common is only usable on Windows, which may affect the cross-platform use of Yolov7net within MAUI？

**Comment by sharpwood** [comment]
System.PlatformNotSupportedException: 'Operation is not supported on this platform.'

**Comment by iwaitu** [comment]
I will make some change for this. I think I should use skiasharp to replace system.drawing.common

**Comment by iwaitu** [comment]
You can find out the detail here: 7912cc7

The new branch was commited named [cross-platform](https://github.com/ivilson/Yolov7net/tree/cross-platform).

Considering cross-platform compatibility, such as supporting mobile development, I have removed numpy support in this new branch to reduce the size of the program package.
