### ISSUE TITLE
新的跨平台分支，识别上好像有些问题。

### ISSUE THREAD

**Issue by sharpwood** [ivilson/Yolov7net#32]
同样的模型，用这个分支识别起来精度特别差，用以前的还有其他yolov8库是没问题的。目前大部分yolo的库用的是ImageSharp，在MAUI Android下面性能特别差。这个项目选择的SkiaSharp没这个问题。但目前精度较差，不知道是不是图片预处理方面还有点问题。

**Comment by iwaitu** [comment]
你的图片进行了预处理吗？

**Comment by sharpwood** [comment]
没有预处理

**Comment by iwaitu** [comment]
你用新的分支在电脑上运行结果如何？我本地测试，准确率和之前版本呢是一样的

**Comment by iwaitu** [comment]
> 没有预处理

我已经修正了代码，不过现在已经没有使用system.drawing 的版本了，只有skiasharp 的
