### ISSUE TITLE
yolov10 only detects 1 class

### ISSUE THREAD

**Issue by Adri1996PowerGirl** [ivilson/Yolov7net#34]
all works perfect, but the output is always only one "prediction". if there is a bench and a person in an image, it detects only one of them.

**Comment by Adri1996PowerGirl** [comment]
i think the "ParseDetect" must be changed to:

                for (int i = 0; i < output.Dimensions[1]; i++)
                {
                    var span = output.Buffer.Span.Slice(i * output.Strides[1]);

**Comment by iwaitu** [comment]
new release 1.0.10  fixed the bug where YOLOv10 inference results only contained one prediction. thanks for your help.

**Comment by iwaitu** [comment]
![](https://raw.githubusercontent.com/ivilson/Yolov7net/master/demo_result_yolov10.jpg)

**Comment by Adri1996PowerGirl** [comment]
thank you for the fast fix. I appreciate your work!
