### ISSUE TITLE
yolo.Predict 方法错误  System.IndexOutOfRangeException:“Index was outside the bounds of the array.”

### ISSUE THREAD

**Issue by LiuCodeDream** [ivilson/Yolov7net#7]
using var yolo = new Yolov7("./Assets/yolov7_training.onnx");
            yolo.SetupYoloDefaultLabels();
            //yolo.SetupLabels(new string[] { "OilBarrel", "FaceShield", "jacket", "trousers", "boots", "shoes", "glove", "safety_hat" });
            Assert.NotNull(yolo);

            using var image = System.Drawing.Image.FromFile("Assets/demo.jpg");
            var ret = yolo.Predict(image);
            Assert.NotNull(ret);
            Assert.True(ret.Count == 1);

**Comment by iwaitu** [comment]
The labels count in your onnx file is less than the length was setup in your setuplabel function
