### ISSUE TITLE
Ddl problem

### ISSUE THREAD

**Issue by TibergynGuillaume** [ivilson/Yolov7net#9]
Hello 

While running my program I constanty have this error : 
Exception thrown: 'System.EntryPointNotFoundException' in Microsoft.ML.OnnxRuntime.dll .
Has anyone encountered this and found a solution?

Greetings

**Comment by iwaitu** [comment]
You need to add this package in your project if you want to use cpu, otherwise you need Microsoft.ML.OnnxRuntim.Gpu  to use gpu
